openapi: 3.0.0
info:
  title: Portrait Extractor API
  description: API for extracting and processing portrait images.
  version: 1.0.0

servers:
  - url: https://pe-1028326783113.us-central1.run.app


paths:
  /portrait_extract/:
    post:
      summary: Extract and process a portrait image.
      description: Accepts an image file, detects a face, crops the face region, and returns it as a Base64-encoded image.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: The portrait image file (PNG, JPG, or JPEG format).
      responses:
        '200':
          description: Portrait image successfully processed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  base64_image:
                    type: string
                    description: Base64-encoded portrait image.
                  single_portrait:
                    type: boolean
                    description: Indicates if only one face was detected in the image.
        '400':
          description: Invalid input or no face detected.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
                  help:
                    type: string
                    description: Suggestion to correct the request format.
        '500':
          description: Server error during image processing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message detailing the server issue.

  /docs:
    get:
      summary: API Documentation
      description: Returns documentation details for the API.
      responses:
        '200':
          description: Documentation content returned successfully.
          content:
            text/html:
              schema:
                type: string

  /:
    get:
      summary: API Index
      description: Returns a welcome message and directs users to the documentation.
      responses:
        '200':
          description: Welcome message returned successfully.
          content:
            text/plain:
              schema:
                type: string
